### PR TITLE
Avoid returning an error to the user on valid message

### PR DESCRIPTION
**Pull request by zbalaton**

### CODE REVIEW

**Comment by zbalaton** [comment]
What about this? Will it be merged or are there any changes needed?

**Comment by zbalaton** [comment]
Hello,
Updated this pull request now with a small patch for more debug messages. Will this be merged sometimes? It's waiting for a while with no comments. Thanks.

**Comment by nikias** [comment]
Hi! Would you mind renaming the MESSAGE_DEVICE_PAIR to MESSAGE_DEVICE_PAIRED? That would be more consistent.

**Comment by nikias** [comment]
Also "Log all receive errors for debugging" should be "Log all received errors for debugging"

**Comment by zbalaton** [comment]
Updated patches according to comments

**Comment by nikias** [comment]
Thanks. I merged it and committed another change that actually makes use of the Paired message passing it to the client through the callback.

**Pull request merged**
