### PR TITLE
filter out devices whose connection_type is USB to fix when devices c…

### PR DESCRIPTION
**Pull request by AngleZhou**
filter out devices whose connection_type is USB to fix when devices connected through WIFI they are also listed.

We encounter this issue when using iproxy to transmit packages from PC to iPhone, it actually connects to some other iPhone which are in the same network but not USB connected. And the real USB connected iPhone is ignored so it cannot get packages from PC.

### CODE REVIEW

**Comment by fishjam** [comment]
This PR can fix  #22 .

**Comment by fishjam** [comment]
@AngleZhou , there is a memory leak. 
```
if (strcmp(dev->connection_type, "USB") == 0) {
...
}
else {
  free(dev);
}

**Comment by fishjam** [comment]
@FunkyM @nikias , could you confirm this PR?
Thanks.

**Comment by jflow** [comment]
I would say this is not the correct fix for the library. The wifi connected devices are needed as Apple is starting to remove USB connects from some devices. So just removing wifi connected devices limited the functionality. Please don't use this PR as the final solution!

**Comment by nikias** [comment]
Guys, I have something in the works to support this properly. No worries.

**Comment by nikias** [comment]
This matter has been resolved with adapting the API.

**Pull request closed without merging**
